### ISSUE TITLE
when pasting in term I donot get full line echo

### ISSUE THREAD

**Issue by drforbin** [cytopia/pwncat#109]
When I paste in shell created with pwncat I donot get full line echo?
Any idea what's wrong?
great tool by the way

**Comment by cytopia** [comment]
@drforbin any chance you can try out the above posted branch and let me know if this fixes the issues on all the use-cases you were facing this?

**Comment by drforbin** [comment]
Hi..I'll do it tonight

**Comment by drforbin** [comment]
It seems to be working fine.
I only did a quick ncat <-> pwncat check.
What was wrong?

**Comment by cytopia** [comment]
The error was non trivial and I was doing a lot of trial&error to figure it out.
In the end I removed the non-blocking select call on stdin: https://github.com/cytopia/pwncat/pull/110/files#diff-70eb7791158dc5e238921ef7dc25ce6a6924dbb39ad728461816c8501b90da7fR3531

I made it blocking again (which doesn't really matter, as it runs in its own thread anyway).
