### ISSUE TITLE
Link to grab netcat no longer works

### ISSUE THREAD

**Issue by emilyanncr** [cytopia/pwncat#112]
The following URL no longer works.  Browsing to it gives a 404 Not Found response (see attached image).  Can you please update?  Thankls.

 https://raw.githubusercontent.com/cytopia/netcat/master/bin/netcat.py 

![netcat](https://user-images.githubusercontent.com/8577656/153775377-04cf541f-cf89-4e5d-a7d9-fb35a8b94d29.jpeg)

**Comment by cytopia** [comment]
@emilyanncr where can I find the link that lead you there?

**Comment by emilyanncr** [comment]
@cytopia https://pypi.org/project/netcat/

**Comment by cytopia** [comment]
>

**Comment by emilyanncr** [comment]
thanks!
